# Generated by Django 5.2.4 on 2025-07-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(help_text='Paste image URL', max_length=500),
        ),
    ]
